
# /home/acefire6/PycharmProjects/compilers-2/compilers1/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '0040FD42D1A0D429E4D125C07EF397A5'
    
_lr_action_items = {'MINUS':([7,8,9,10,11,12,19,20,21,22,23,24,25,],[13,-12,15,-13,-11,13,-14,-7,-5,-6,-9,-8,-4,]),'LPAREN':([4,6,13,14,15,16,17,18,],[6,6,6,6,6,6,6,6,]),'$end':([2,3,5,7,8,9,10,11,19,20,21,22,23,24,25,],[-2,0,-1,-3,-12,-10,-13,-11,-14,-7,-5,-6,-9,-8,-4,]),'FLOAT_LITERAL':([4,6,13,14,15,16,17,18,],[10,10,10,10,10,10,10,10,]),'TIMES':([8,9,10,11,19,20,21,22,23,24,25,],[-12,17,-13,-11,-14,17,17,17,17,17,17,]),'RPAREN':([8,9,10,11,12,19,20,21,22,23,24,25,],[-12,-10,-13,-11,19,-14,-7,-5,-6,-9,-8,-4,]),'ID':([0,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,],[1,-2,1,8,-1,8,-3,-12,-10,-13,-11,8,8,8,8,8,8,-14,-7,-5,-6,-9,-8,-4,]),'DIVIDE':([8,9,10,11,19,20,21,22,23,24,25,],[-12,16,-13,-11,-14,16,16,16,16,16,16,]),'EQUALS':([1,],[4,]),'PLUS':([7,8,9,10,11,12,19,20,21,22,23,24,25,],[14,-12,18,-13,-11,14,-14,-7,-5,-6,-9,-8,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([4,6,],[7,12,]),'term':([4,6,13,14,15,16,17,18,],[9,9,20,21,22,23,24,25,]),'factor':([4,6,13,14,15,16,17,18,],[11,11,11,11,11,11,11,11,]),'assign':([0,3,],[2,5,]),'program':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program assign','program',2,'p_program','parse_ula.py',11),
  ('program -> assign','program',1,'p_program_assign','parse_ula.py',16),
  ('assign -> ID EQUALS expr','assign',3,'p_assign_expr','parse_ula.py',21),
  ('expr -> term PLUS term','expr',3,'p_expr_plus','parse_ula.py',26),
  ('expr -> expr PLUS term','expr',3,'p_expr_plus','parse_ula.py',27),
  ('expr -> term MINUS term','expr',3,'p_expr_minus','parse_ula.py',32),
  ('expr -> expr MINUS term','expr',3,'p_expr_minus','parse_ula.py',33),
  ('term -> term TIMES term','term',3,'p_term_mul','parse_ula.py',38),
  ('term -> term DIVIDE term','term',3,'p_term_div','parse_ula.py',43),
  ('expr -> term','expr',1,'p_expr_term','parse_ula.py',48),
  ('term -> factor','term',1,'p_term_factor','parse_ula.py',53),
  ('factor -> ID','factor',1,'p_factor_id','parse_ula.py',58),
  ('factor -> FLOAT_LITERAL','factor',1,'p_factor','parse_ula.py',63),
  ('factor -> LPAREN expr RPAREN','factor',3,'p_factor_expr','parse_ula.py',68),
]
